### ISSUE TITLE
Couldn't attach disk, err: stat

### ISSUE THREAD

**Issue by survivant** [openebs/cstor-operators#251]
I got this error in my pod in the event section

````
054b55e7" : rpc error: code = Internal desc = failed to find device path: [], last error seen: Couldn't attach disk, err: stat /dev/disk/by-path/ip-10.103.120.238:3260-iscsi-iqn.2016-09.com.openebs.cstor:pvc-38394e5a-c078-4a6b-8c2d-394b054b55e7-lun-0: no such file or directory
````

but OpenEBS pods look fine
````
root@test-pcl109:~# kubectl get pods -n openebs | grep pvc-38394e5a-c078-4a6b-8c2d-394b054b55e7
pvc-38394e5a-c078-4a6b-8c2d-394b054b55e7-target-b95977f9f-2b4wv   3/3     Running   0          12m
root@test-pcl109:~#
````

but I don't have more details because I destroy everything to reinstall my apps.

I'm using OpenEBS 2.5.0

**Comment by mittachaitu** [comment]
Can we get following outputs from the node where the application pod is running?
- sudo iscsiadm -m session
- sudo iscsiadm -m session -P 3
- ls -lrth /dev/disk/by-path
- fdisk -l
- lsblk
- cat /etc/os-release
And logs of a csi-node driver daemon running on the same node. The above details may help to dig into the issue further.

**Comment by survivant** [comment]
sorry, but I filled the issue long time ago.  I'll not be able to reproduce the issue

**Comment by prateekpandey14** [comment]
Closing for now, feel free to open, in case we hit the issue again.
