### ISSUE TITLE
Provide alternate image registry to dockerhub 

### ISSUE THREAD

**Issue by anthr76** [openebs/cstor-operators#329]
Hello,

In order to combat dockerhub's imposed rate limits it would be great to host these images on ghcr or quay.io. Are there on any thoughts from the community on this initiation?

**Comment by prateekpandey14** [comment]
@anthr76 from v2.9.0 release onwards, we are  again going to push the multi arch images in quay.io (multi arch images not supported earlier).

There were some transisition happening towards github actions in CI/CD and release workflow with multi arch images , which is completed now.

**Comment by anthr76** [comment]
That's great!

**Comment by dirtycajunrice** [comment]
Does this include all images? The ones that I currently have deploy are: 
```
openebs/cspc-operator:2.8.0
openebs/cstor-csi-driver:2.8.0
openebs/cstor-istgt:2.8.0
openebs/cstor-pool-manager:2.8.0
openebs/cstor-pool:2.8.0
openebs/cstor-volume-manager:2.8.0
openebs/cstor-webhook:2.8.0
openebs/cvc-operator:2.8.0
openebs/m-exporter:2.8.0
openebs/node-disk-manager:1.4.0
openebs/node-disk-operator:1.4.0
```
additionally if the images are already going into github ci/cd why would it not also push to ghcr.io? it would be nearly instant

**Comment by prateekpandey14** [comment]
>Does this include all images? The ones that I currently have deploy are:

@dirtycajunrice yes, it include all the images. We are yet to decide to push the images in ghcr.io.

**Comment by akhilerm** [comment]
Raised [PR](https://github.com/openebs/linux-utils/pull/16) in linux-utils to push image to ghcr. cc: @kmova

**Comment by kmova** [comment]
@anthr76 @dirtycajunrice - just reaching out to check if you would be interested in helping out adding the pushing to ghcr.io. 

The steps to push are pretty straightforward and can be seen in this PR. https://github.com/openebs/linux-utils/pull/16
