### ISSUE TITLE
Failed to install by helm

### ISSUE THREAD

**Issue by laingke** [openebs/cstor-operators#356]
When using `helm install`, it occur below error:

`Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "VolumeSnapshotClass" in version "snapshot.storage.k8s.io/v1"`

Kubernetes Version: v1.21.1

**Comment by kmova** [comment]
Hi @laingke - can you try with the latest helm. This is fixed via #361 and #362

**Comment by prateekpandey14** [comment]
closing , fixed in PR mentioned above comment
